steps:
- id: "update swagger screen files"
  name: "swaggerapi/swagger-codegen-cli"
  entrypoint: ash
  args:
      - -c
      - |
        java -jar /opt/swagger-codegen-cli/swagger-codegen-cli.jar generate -i ./swagger.yaml -l nodejs-server -o ./$_OUTPUT_DIR
        cp app.yaml ./$_OUTPUT_DIR

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/bash'
  args:
      - '-c'
      - |
        gcloud app versions list --service=default | grep default | sort -rk 4,4 | awk '{print $2}' | tail -n +${_REMAIN_VERSION_COUNT} | xargs -I {} gcloud app versions delete {}
        cd $_OUTPUT_DIR
        gcloud app deploy
substitutions:
    _REMAIN_VERSION_COUNT: "4"
    _OUTPUT_DIR: "swagger-c"
    
